typography_spectrum: 1
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6802253
analytics:
  google: null
  facebook: null
  twitter: null
name: l@W
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: REBORN
    id: f69657f8-5227-4278-a444-d317718974c3
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: null
purpose: []
